In [1]:
import pandas as pd

In [2]:
#step 1 data collection
data = pd.read_csv('Housing.csv')

In [3]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
#step 2 : data understanding
data.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [6]:
data.shape #shape is used for x , y axis

(545, 13)

In [7]:
data.size #product of x*y

7085

In [8]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [9]:
#model training
from sklearn.neighbors import KNeighborsRegressor # same for KNeighborsClassifier

In [10]:
#data preprocessing step 3
from sklearn.preprocessing import LabelEncoder # label encoder converts the strings into the numbers

In [11]:
le = LabelEncoder()

In [12]:
sampledata =['mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus']

In [13]:
for i in sampledata:
  data[i]= le.fit_transform(data[i])

In [14]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

In [16]:
x= data.iloc[: ,1:].values #iloc menas integer location, integer location[row,colums] iloc[: , :] all rows and all columns
y = data['price'].values

In [17]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test = train_test_split(x,y,test_size=0.2 , random_state =2)

In [18]:
knnmodel = KNeighborsRegressor(n_neighbors=111) #if not ension the n_neighbors it take default value as 5
#train the model
knnmodel.fit(x_train,y_train)# here model train, then after training the model it is ready for testing

KNeighborsRegressor(n_neighbors=111)

In [19]:
y_pred =knnmodel.predict(x_test) #knnmoedl is the nickname for the Kneighbot=rs Regressor , prefdict for testigng , after moddel fitting

In [20]:
import math # math librarry to import # for regressor , mean error, which is represented as the +-error  mean error
from sklearn.metrics import mean_squared_error
meanerro = math.sqrt(mean_squared_error(y_pred,y_test))
print(f"the value of mean squared error is {meanerro}")

the value of mean squared error is 1661770.6519246066

In [21]:
#evaluation for increase accuracy  or decrese error
from sklearn.metrics import root_mean_squared_error
error =root_mean_squared_error(y_pred,y_test)

In [22]:
print(error)#means the predict the utput it result a differece of actual value or addition of actual value of the error called ad error rate
#sklearn - model_slection for train_test_split
#sklearn model loading neighbours
#for classifies - accuracy_score metrics f slearn #

1661770.6519246066

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
linermodel =LinearRegression()

In [26]:
linermodel.fit(x_train , y_train)

LinearRegression()

In [27]:
y_pred = linermodel.predict(x_test)

In [28]:
from sklearn.metrics import root_mean_squared_error

In [29]:
print(root_mean_squared_error(y_pred,y_test))

1136290.9401069537